In [1]:
import numpy as np 
import pandas as pd

In [5]:
df = pd.read_excel("IPL.xls")
df.head()

,Match_Number,Match,Date,Year,Venue,Team_Batting_First,Team_Batting_Second,Bat_First_Runs_Scored,Bat_First_Wickets_Lost,Bat_First_Overs_Consumed,...,Bat_Second_10_ov_score,Bat_Second_10_ov_wkts_lost,Bat_Second_10_ov_Req_RR,Bat_Second_15_ov_score,Bat_Second_15_ov_wkts_lost,Bat_Second_15_ov_Req_RR,Bat_Second_20_ov_score,Bat_Second_20_ov_wkts_lost,Match_Time,Duckworth Lewis Used
0,1,League Match,Apr 18,2008,Bangalore,Kolkata,Bangalore,222,3,20.0,...,51.0,7.0,17.2,81.0,9.0,28.4,NaN,NaN,Evening,NaN
1,2,League Match,Apr 19,2008,Mohali,Chennai,Punjab,240,5,20.0,...,110.0,1.0,13.1,165.0,3.0,15.2,207.0,4.0,Afternoon,NaN
2,3,League Match,Apr 19,2008,Delhi,Rajasthan,Delhi,129,8,20.0,...,86.0,1.0,4.4,128.0,1.0,0.4,NaN,NaN,Evening,NaN
3,4,League Match,Apr 20,2008,Kolkata,Hyderabad,Kolkata,110,10,18.4,...,38.0,3.0,7.3,81.0,4.0,6.0,NaN,NaN,Afternoon,NaN
4,5,League Match,Apr 20,2008,Mumbai,Mumbai,Bangalore,165,6,20.0,...,76.0,3.0,9.0,118.0,4.0,9.6,166.0,5.0,Evening,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 43 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Match_Number                514 non-null    int64
 1   Match                       514 non-null    object
 2   Date                        514 non-null    object
 3   Year                        514 non-null    int64
 4   Venue                       514 non-null    object
 5   Team_Batting_First          514 non-null    object
 6   Team_Batting_Second         514 non-null    object
 7   Bat_First_Runs_Scored       514 non-null    int64
 8   Bat_First_Wickets_Lost      514 non-null    int64
 9   Bat_First_Overs_Consumed    514 non-null    float64
 10  Bat_First_Overs_Allocated   514 non-null    int64
 11  Bat_Second_Runs_Scored      514 non-null    int64
 12  Bat_Second_Wickets_Lost     514 non-null    int64
 13  Bat_Second_Overs_Consumed   514 non-null    float64
 14  Bat_Second_Overs_Allocated  514 non-null    float64
 15  Winner                      514 non-null    object
 16  Winning_Team                514 non-null    object
 17  Winning_Margin              508 non-null    float64
 18  Win_Type                    508 non-null    object
 19  Bat_First_Run_Rate          514 non-null    float64
 20  Bat_Second_Run_Rate         514 non-null    float64
 21  Balls_Remaining             514 non-null    float64
 22  Bat_First_5_ov_score        514 non-null    int64
 23  Bat_First_5_ov_wkts_lost    514 non-null    int64
 24  Bat_First_10_ov_score       513 non-null    float64
 25  Bat_First_10_ov_wkts_lost   513 non-null    float64
 26  Bat_First_15_ov_score       506 non-null    float64
 27  Bat_First_15_ov_wkts_lost   506 non-null    float64
 28  Bat_First_20_ov_score       501 non-null    float64
 29  Bat_First_20_ov_wkts_lost   501 non-null    float64
 30  Bat_Second_5_ov_score       514 non-null    int64
 31  Bat_Second_5_ov_wkts_lost   514 non-null    int64
 32  Bat_Second_5_ov_Req_RR      512 non-null    float64
 33  Bat_Second_10_ov_score      506 non-null    float64
 34  Bat_Second_10_ov_wkts_lost  506 non-null    float64
 35  Bat_Second_10_ov_Req_RR     503 non-null    float64
 36  Bat_Second_15_ov_score      478 non-null    float64
 37  Bat_Second_15_ov_wkts_lost  478 non-null    float64
 38  Bat_Second_15_ov_Req_RR     468 non-null    float64
 39  Bat_Second_20_ov_score      305 non-null    float64
 40  Bat_Second_20_ov_wkts_lost  305 non-null    float64
 41  Match_Time                  514 non-null    object
 42  Duckworth Lewis Used        7 non-null      object
dtypes: float64(22), int64(11), object(10)
memory usage: 172.8+ KB

In [20]:
one = df[df['Winner'] == "Match tied"]

In [21]:
two = df[df['Balls_Remaining'] <= 3]

In [22]:
three = df[
    (df['Winning_Team'] == "Chasing") &
    (df['Bat_Second_Wickets_Lost'] >= 9)
]

In [23]:
four = df[
    (df['Winning_Team'] == "FirstBatting") &
    (df['Winning_Margin'] <= 5)
]

In [25]:
close_matches = pd.concat([one, two, three, four])
close_matches

,Match_Number,Match,Date,Year,Venue,Team_Batting_First,Team_Batting_Second,Bat_First_Runs_Scored,Bat_First_Wickets_Lost,Bat_First_Overs_Consumed,...,Bat_Second_10_ov_score,Bat_Second_10_ov_wkts_lost,Bat_Second_10_ov_Req_RR,Bat_Second_15_ov_score,Bat_Second_15_ov_wkts_lost,Bat_Second_15_ov_Req_RR,Bat_Second_20_ov_score,Bat_Second_20_ov_wkts_lost,Match_Time,Duckworth Lewis Used
66,67,League Match,Apr 23,2009,Cape Town,Rajasthan,Kolkata,150,6,20.0,...,67.0,3.0,8.4,98.0,5.0,10.6,150.0,8.0,Evening,NaN
130,131,League Match,Mar 21,2010,Chennai,Punjab,Chennai,136,8,20.0,...,73.0,1.0,6.4,109.0,4.0,5.6,136.0,7.0,Evening,NaN
327,328,League Match,Apr 7,2013,Hyderabad,Bangalore,Hyderabad,130,8,20.0,...,56.0,3.0,7.5,91.0,4.0,8.0,130.0,7.0,Evening,NaN
341,342,League Match,Apr 16,2013,Bangalore,Delhi,Bangalore,152,5,20.0,...,84.0,2.0,6.9,126.0,2.0,5.4,152.0,7.0,Evening,NaN
415,416,League Match,Apr 29,2014,Abu Dhabi,Rajasthan,Kolkata,152,5,20.0,...,59.0,2.0,9.4,101.0,4.0,10.4,152.0,8.0,Evening,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458,459,League Match,Apr 9,2015,Chennai,Chennai,Delhi,150,7,20.0,...,67.0,3.0,8.4,102.0,5.0,9.8,149.0,9.0,Evening,NaN
469,470,League Match,Apr 18,2015,Visakhapatnam,Delhi,Hyderabad,167,4,20.0,...,69.0,2.0,9.9,110.0,3.0,11.6,163.0,8.0,Afternoon,NaN
483,484,League Match,Apr 28,2015,Chennai,Chennai,Kolkata,134,6,20.0,...,70.0,3.0,6.5,90.0,4.0,9.0,132.0,9.0,Evening,NaN
502,503,League Match,May 11,2015,Hyderabad,Hyderabad,Punjab,185,5,20.0,...,70.0,4.0,11.6,104.0,6.0,16.4,180.0,7.0,Evening,NaN
505,506,League Match,May 14,2015,Mumbai,Mumbai,Kolkata,171,4,20.0,...,74.0,2.0,9.8,122.0,4.0,10.0,166.0,7.0,Evening,NaN

In [30]:
close_matches[close_matches["Year"] == 2008]

,Match_Number,Match,Date,Year,Venue,Team_Batting_First,Team_Batting_Second,Bat_First_Runs_Scored,Bat_First_Wickets_Lost,Bat_First_Overs_Consumed,...,Bat_Second_10_ov_score,Bat_Second_10_ov_wkts_lost,Bat_Second_10_ov_Req_RR,Bat_Second_15_ov_score,Bat_Second_15_ov_wkts_lost,Bat_Second_15_ov_Req_RR,Bat_Second_20_ov_score,Bat_Second_20_ov_wkts_lost,Match_Time,Duckworth Lewis Used
1,2,League Match,Apr 19,2008,Mohali,Chennai,Punjab,240,5,20.0,...,110.0,1.0,13.1,165.0,3.0,15.2,207.0,4.0,Afternoon,NaN
4,5,League Match,Apr 20,2008,Mumbai,Mumbai,Bangalore,165,6,20.0,...,76.0,3.0,9.0,118.0,4.0,9.6,166.0,5.0,Evening,NaN
7,8,League Match,Apr 23,2008,Chennai,Chennai,Mumbai,208,5,20.0,...,83.0,3.0,12.6,134.0,5.0,15.0,202.0,7.0,Evening,NaN
8,9,League Match,Apr 24,2008,Hyderabad,Hyderabad,Rajasthan,214,5,20.0,...,114.0,2.0,10.1,159.0,3.0,11.2,217.0,7.0,Evening,NaN
9,10,League Match,Apr 25,2008,Mohali,Punjab,Mumbai,182,10,20.0,...,67.0,4.0,11.6,101.0,7.0,16.4,116.0,9.0,Evening,NaN
12,13,League Match,Apr 27,2008,Mohali,Delhi,Punjab,158,8,20.0,...,81.0,3.0,7.8,123.0,4.0,7.2,162.0,6.0,Afternoon,NaN
14,15,League Match,Apr 28,2008,Bangalore,Chennai,Bangalore,178,5,20.0,...,93.0,1.0,8.6,132.0,3.0,9.4,165.0,10.0,Evening,NaN
16,17,League Match,Apr 30,2008,Delhi,Delhi,Bangalore,191,5,20.0,...,83.0,3.0,10.9,134.0,3.0,11.6,181.0,5.0,Evening,NaN
20,21,League Match,May 3,2008,Bangalore,Bangalore,Hyderabad,156,8,20.0,...,63.0,2.0,9.4,112.0,2.0,9.0,153.0,6.0,Afternoon,NaN
21,22,League Match,May 3,2008,Mohali,Punjab,Kolkata,178,6,20.0,...,52.0,5.0,12.7,101.0,5.0,15.6,169.0,6.0,Evening,NaN
27,28,League Match,May 8,2008,Delhi,Delhi,Chennai,187,5,20.0,...,98.0,2.0,9.0,142.0,4.0,9.2,188.0,6.0,Afternoon,NaN
28,29,League Match,May 8,2008,Kolkata,Kolkata,Bangalore,129,7,16.0,...,53.0,3.0,13.0,111.0,4.0,20.0,NaN,NaN,Evening,NaN
30,31,League Match,May 10,2008,Chennai,Chennai,Punjab,181,4,20.0,...,76.0,2.0,10.6,115.0,6.0,13.4,163.0,9.0,Evening,NaN
31,32,League Match,May 11,2008,Hyderabad,Kolkata,Hyderabad,204,4,20.0,...,74.0,4.0,13.1,125.0,6.0,16.0,181.0,7.0,Afternoon,NaN
36,37,League Match,May 15,2008,Delhi,Delhi,Hyderabad,194,4,20.0,...,84.0,3.0,11.1,128.0,4.0,13.4,182.0,9.0,Evening,NaN
38,39,League Match,May 17,2008,Jaipur,Rajasthan,Bangalore,197,1,20.0,...,38.0,4.0,16.0,83.0,7.0,23.0,132.0,9.0,Afternoon,NaN
39,40,League Match,May 17,2008,Delhi,Delhi,Punjab,118,4,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Evening,D/L
40,41,League Match,May 18,2008,Kolkata,Kolkata,Chennai,149,5,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afternoon,D/L
41,42,League Match,May 18,2008,Hyderabad,Mumbai,Hyderabad,178,7,20.0,...,59.0,4.0,12.0,106.0,4.0,14.6,153.0,7.0,Evening,NaN
44,45,League Match,May 21,2008,Mumbai,Punjab,Mumbai,189,4,20.0,...,90.0,2.0,10.0,144.0,3.0,9.2,188.0,10.0,Afternoon,NaN
45,46,League Match,May 21,2008,Chennai,Bangalore,Chennai,126,8,20.0,...,61.0,1.0,6.6,91.0,4.0,7.2,111.0,8.0,Evening,NaN
46,47,League Match,May 23,2008,Mohali,Hyderabad,Punjab,175,4,20.0,...,101.0,1.0,7.5,135.0,2.0,8.2,178.0,4.0,Evening,NaN
47,48,League Match,May 24,2008,Chennai,Rajasthan,Chennai,211,5,20.0,...,99.0,2.0,11.3,157.0,3.0,11.0,201.0,7.0,Afternoon,NaN
48,49,League Match,May 24,2008,Delhi,Mumbai,Delhi,176,8,20.0,...,88.0,2.0,8.9,130.0,5.0,9.4,179.0,5.0,Evening,NaN
50,51,League Match,May 25,2008,Kolkata,Punjab,Kolkata,174,6,20.0,...,74.0,4.0,10.1,104.0,5.0,14.2,175.0,7.0,Evening,NaN
51,52,League Match,May 26,2008,Jaipur,Mumbai,Rajasthan,145,7,20.0,...,67.0,3.0,7.9,90.0,5.0,11.2,146.0,5.0,Evening,NaN
54,55,League Match,May 28,2008,Mohali,Punjab,Rajasthan,221,3,20.0,...,67.0,2.0,15.5,140.0,5.0,16.4,180.0,7.0,Evening,NaN
57,58,Final,Jun 1,2008,Mumbai,Chennai,Rajasthan,163,5,20.0,...,75.0,3.0,8.9,112.0,4.0,10.4,164.0,7.0,Evening,NaN
20,21,League Match,May 3,2008,Bangalore,Bangalore,Hyderabad,156,8,20.0,...,63.0,2.0,9.4,112.0,2.0,9.0,153.0,6.0,Afternoon,NaN
28,29,League Match,May 8,2008,Kolkata,Kolkata,Bangalore,129,7,16.0,...,53.0,3.0,13.0,111.0,4.0,20.0,NaN,NaN,Evening,NaN
44,45,League Match,May 21,2008,Mumbai,Punjab,Mumbai,189,4,20.0,...,90.0,2.0,10.0,144.0,3.0,9.2,188.0,10.0,Afternoon,NaN

In [31]:
close_matches.groupby('Year').size()

Year
2008    31
2009    37
2010    31
2011    36
2012    49
2013    46
2014    36
2015    46
dtype: int64

In [39]:
teams = [
    'Chennai',
    'Hyderabad',
    'Mumbai',
    'Kolkata'
]

for team in teams:

    A = len(df[df['Winner'] == team])

    B = len(
        df[
            (df['Winner'] == team) &
            (df['Winning_Team'] == 'FirstBatting')
        ]
    )

    percent = (B / A) * 100

    print(team, round(percent,2))

Chennai 56.96
Hyderabad 60.78
Mumbai 56.16
Kolkata 41.67

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 43 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Match_Number                514 non-null    int64
 1   Match                       514 non-null    object
 2   Date                        514 non-null    object
 3   Year                        514 non-null    int64
 4   Venue                       514 non-null    object
 5   Team_Batting_First          514 non-null    object
 6   Team_Batting_Second         514 non-null    object
 7   Bat_First_Runs_Scored       514 non-null    int64
 8   Bat_First_Wickets_Lost      514 non-null    int64
 9   Bat_First_Overs_Consumed    514 non-null    float64
 10  Bat_First_Overs_Allocated   514 non-null    int64
 11  Bat_Second_Runs_Scored      514 non-null    int64
 12  Bat_Second_Wickets_Lost     514 non-null    int64
 13  Bat_Second_Overs_Consumed   514 non-null    float64
 14  Bat_Second_Overs_Allocated  514 non-null    float64
 15  Winner                      514 non-null    object
 16  Winning_Team                514 non-null    object
 17  Winning_Margin              508 non-null    float64
 18  Win_Type                    508 non-null    object
 19  Bat_First_Run_Rate          514 non-null    float64
 20  Bat_Second_Run_Rate         514 non-null    float64
 21  Balls_Remaining             514 non-null    float64
 22  Bat_First_5_ov_score        514 non-null    int64
 23  Bat_First_5_ov_wkts_lost    514 non-null    int64
 24  Bat_First_10_ov_score       513 non-null    float64
 25  Bat_First_10_ov_wkts_lost   513 non-null    float64
 26  Bat_First_15_ov_score       506 non-null    float64
 27  Bat_First_15_ov_wkts_lost   506 non-null    float64
 28  Bat_First_20_ov_score       501 non-null    float64
 29  Bat_First_20_ov_wkts_lost   501 non-null    float64
 30  Bat_Second_5_ov_score       514 non-null    int64
 31  Bat_Second_5_ov_wkts_lost   514 non-null    int64
 32  Bat_Second_5_ov_Req_RR      512 non-null    float64
 33  Bat_Second_10_ov_score      506 non-null    float64
 34  Bat_Second_10_ov_wkts_lost  506 non-null    float64
 35  Bat_Second_10_ov_Req_RR     503 non-null    float64
 36  Bat_Second_15_ov_score      478 non-null    float64
 37  Bat_Second_15_ov_wkts_lost  478 non-null    float64
 38  Bat_Second_15_ov_Req_RR     468 non-null    float64
 39  Bat_Second_20_ov_score      305 non-null    float64
 40  Bat_Second_20_ov_wkts_lost  305 non-null    float64
 41  Match_Time                  514 non-null    object
 42  Duckworth Lewis Used        7 non-null      object
dtypes: float64(22), int64(11), object(10)
memory usage: 172.8+ KB

In [45]:
df[(df['Bat_Second_15_ov_wkts_lost'] == 4) & (df['Bat_First_Runs_Scored'] - df['Bat_Second_15_ov_score'] + 1 == 33) & (df['Winning_Team'] == "FirstBatting")]

,Match_Number,Match,Date,Year,Venue,Team_Batting_First,Team_Batting_Second,Bat_First_Runs_Scored,Bat_First_Wickets_Lost,Bat_First_Overs_Consumed,...,Bat_Second_10_ov_score,Bat_Second_10_ov_wkts_lost,Bat_Second_10_ov_Req_RR,Bat_Second_15_ov_score,Bat_Second_15_ov_wkts_lost,Bat_Second_15_ov_Req_RR,Bat_Second_20_ov_score,Bat_Second_20_ov_wkts_lost,Match_Time,Duckworth Lewis Used
342,343,League Match,Apr 17,2013,Pune,Hyderabad,Pune,119,8,20.0,...,65.0,3.0,5.5,87.0,4.0,6.6,NaN,NaN,Afternoon,NaN

In [52]:
df[(df['Bat_First_15_ov_wkts_lost'] == 2) & (df['Bat_First_20_ov_score'] - df['Bat_First_15_ov_score'] < 25)]

,Match_Number,Match,Date,Year,Venue,Team_Batting_First,Team_Batting_Second,Bat_First_Runs_Scored,Bat_First_Wickets_Lost,Bat_First_Overs_Consumed,...,Bat_Second_10_ov_score,Bat_Second_10_ov_wkts_lost,Bat_Second_10_ov_Req_RR,Bat_Second_15_ov_score,Bat_Second_15_ov_wkts_lost,Bat_Second_15_ov_Req_RR,Bat_Second_20_ov_score,Bat_Second_20_ov_wkts_lost,Match_Time,Duckworth Lewis Used
100,101,League Match,May 14,2009,Durban,Rajasthan,Mumbai,145,7,20.0,...,54.0,3.0,9.2,98.0,5.0,9.6,143.0,10.0,Evening,NaN